name: govuln
on:
    pull_request:

jobs:
    govulncheck_job:
        runs-on: ubuntu-latest
        name: Run govulncheck
        steps:
            - id: govulncheck
              uses: golang/govulncheck-action@v1
              with:
                  go-version-input: 1.22
                  check-latest: true
                  go-package: ./...
